In [22]:
import pandas as pd 
import re
import numpy as np

In [3]:
#Read webtext_original_filtered_250.tsv
df = pd.read_csv('webtext_original_filtered_250.tsv', sep='\t')
df_full = pd.read_csv('webtext_original_full.tsv', sep = '\t')

In [4]:
df

,Unnamed: 0,text_full,NCESSCH
0,0,"[('http://www.maef.net/', 'False', '0', ""Menu\...",1.001970e+10
1,1,"[('https://www.kgbsd.org/ketchikancharter', 'F...",2.001500e+10
2,2,"[('http://tongassschool.org/', 'False', '0', '...",2.001500e+10
3,3,"[('https://www.asdk12.org/aquarian', 'False', ...",2.001800e+10
4,4,"[('http://winterberrycharterschool.com/', 'Fal...",2.001800e+10
...,...,...,...
6458,6458,"[('http://www.snowyrangeacademy.org/', 'False'...",5.600730e+11
6459,6459,[('http://www.laramiemontessori.org/index.html...,5.600730e+11
6460,6460,"[('https://www.fcsd38.org/', 'False', '0', ""Fr...",5.600960e+11
6461,6461,"[('https://poderacademy.com/', 'False', '0', '...",5.601980e+11
6462,6462,"[('https://poderacademy.com/', 'False', '0', '...",5.601980e+11

In [5]:
df_full

,Unnamed: 0,text_full,NCESSCH
0,0,"[('https://099.clayton.k12.ga.us/', 'False', '...",130123003896
1,1,"[('https://198.clayton.k12.ga.us/', 'False', '...",130123003687
2,2,"[('http://21stcenturypa.com/wp/', 'False', '0'...",350006000811
3,3,"[('http://a3school.org/', 'False', '0', 'Downl...",411167001641
4,4,"[('https://www.aaechighschools.com/index.php',...",40010601892
...,...,...,...
6499,6499,"[('https://youth-ranch.org/', 'False', '0', ' ...",480022711321
6500,6500,[('https://zenithacademy.squarespace.com/zenit...,390157605848
6501,6501,[('https://zenithacademy.squarespace.com/zenit...,390139605579
6502,6502,[('https://www.kippdc.org/our-schools/kipp-dc-...,110003100427
6503,6503,[('https://www.kippdc.org/our-schools/kipp-dc-...,110003100452

In [6]:
len(df["text_full"][0])

145747

In [7]:
df["text_full"][1]

'[(\'https://www.kgbsd.org/ketchikancharter\', \'False\', \'0\', \'Skip to Main Content\\nDistrict Home\\nSelect a School...\\nSelect a School\\nKetchikan High School\\nRevilla High School\\nFast Track\\nSchoenbar Middle School\\nFawn Mountain Elementary School\\nHoughtaling Elementary School\\nPoint Higgins Elementary School\\nKetchikan Charter School (K-8)\\nSign In\\nRegister\\nSearch Our Site\\nHome\\n\\rAbout\\n"\\r\\r\\nSchool Profile\\nKCS School Creed\\nCore Knowledge\\nCore Knowledge Language Arts\\nPearson enVisionmath\\n\\rContact Us\\n"\\r\\r\\nKCS Contact Information\\nStaff Members\\n\\rClasses & Programs\\n"\\r\\nKindergarten - Becky King\\n1st Grade - Maria Neufeldt\\n2nd Grade - Tom Neufeldt\\n3rd Grade - Elizabeth Avila\\n4th Grade - Danielle Hewitt\\n5th Grade - Joelle Gefre\\nLanguage Arts MS - Erin Henderson\\nMath & Science MS - Jacob Alguire\\nSocial Studies & P.E. MS - Greg Gass\\nMusic - Julie Cron\\nTechnology - Julie Cron\\nArt - Halli Kenoyer\\nSpecial Services - Terri Schultz\\nRTI & Testing Coordinator - Kayla Livingston\\nLibrary - Marie Mecham\\nESL - Jane Hanchett\\nJamie Morelli, SLP\\n\\rParents\\n"\\r\\r\\nCharter Chatter\\nReport Card to the Public\\nSchool & Parent Involvement\\nSchool Forms & Documents\\nEnrollment Information\\nBus Schedule\\nenVision Math Parent Guide\\n\\rAPC\\n"\\r\\r\\nAbout the APC\\nPolicy Manual\\nCommittee Members\\nMinutes\\nAgenda\\nPrincipal Evaluation\\n\\rStaff\\n"\\r\\r\\nCalendar\\nUpcoming Events \\nFriday\\nLAST DAY OF SCHOOL\\n8:00 AM - 9:00 AM\\r         \\nEND OF TRIMESTER 3\\nJune 14, 2018\\n6:00 PM - 8:00 PM\\r         \\nAPC MEETING\\nView Calendar\\nMay 29th -\\xa0June 1st\\nMANAGING TIME\\nList all tasks for a particular day or week.\\nEstimate the time needed to complete each task.\\nPlan for delays, setbacks, and problems.\\nImplement a daily schedule that includes planned tasks.\\nEvaluate your time-management plan for effectiveness.\\nComments (-1)\\nComments (-1)\\nComments (-1)\\nCHARTER\\xa0\\nCHATTER\\nSchool News\\nSUMMER ENRICHMENT CAMP AT KCS\\nGrades 1-6, June 11-21st, Monday-Thursday, 8 am - 12 noon\\nThis is a\\xa0\\nfree enrichment program for elementary age \\nstudents to explore their heritage.\\nTo enroll your child, please complete the questions on the form and return \\nto your child\\\'s teacher by June 5th, 2018\\nSummer Enrichment Camp\\nTHE 2017-2018 SCHOOL YEAR IS COMING TO AN END\\nPLEASE MAKE SURE YOUR STUDENT HAS ALL OF THEIR BOOKS TURNED IN AND THEIR LUNCH BALANCES PAID\\nTHE OFFICE WILL BE OPEN UNTIL THE END OF THE DAY ON WEDNESDAY, JUNE 13TH\\nHAVE A GREAT SUMMER!\\xa0\\nLUNCH BALANCE\\nPLEASE CHECK YOUR STUDENTS LUNCH ACCOUNT\\nWE ARE ALMOST AT THE END OF THE SCHOOL YEAR AND WOULD LIKE TO SEE ALL LUNCH ACCOUNTS AT A POSITIVE BALANCE\\nTHANK YOU FOR TAKING CARE OF THIS IN A TIMELY MANNER!\\nKCS 8th GRADE GRADUATION\\nJUNE 5TH\\n6:00 PM IN THE KCS GYM\\nKETCHIKAN CHARTER/MIDDLE SCHOOL\\n2018-2019\\nENROLLMENT IS NOW OPEN\\nKCS is now accepting registration for the 2018-2019 school year.\\nRegistration packets are online or you\\nmay stop by the office anytime, \\nM-F from 7:45 am - 3:15 pm, to pick up a registration packet.\\xa0\\nSpace is limited, so it is very important to return the registration packet \\nalong with your child\\\'s \\nbirth certificate and immunization records.\\xa0\\nIf your student is already enrolled in another school in the district and wanting to transfer to KCS stop by the office to fill out a transfer form.\\nKetchikan Charter School is Celebrating their 20th Anniversary this year\\nOur school will be hosting and participating in several events throughout the year-the largest of which being 20 community service projects.\\nWe plan to have two events per month and hope to raise the public\\\'s awareness of our school and how much we appreciate them, and that we are a longstanding part of this community.\\nWe hope to serve the community through education.\\nKCS MAY SERVICE PROJECTS\\nMIDDLE SCHOOL WILL HAVE A CLEANUP AS PART \\nOF THEIR CAMPING EXPERIENCE.\\nROBOTICS WILL BE ORGANIZING A FOOD DRIVE.\\n3rd and 4th Grade Beach Cleanup May 22nd\\xa0\\nKCS APRIL SERVICE PROJECTS\\nKINDERGARTEN AND 5TH GRADE WILL HAVE AN \\nEARTH DAY CLEANUP ON APRIL 20TH\\nKCS MARCH SERVICE PROJECTS\\nWe will be working with the \\nFirst City Council on Cancer.\\nMARCH MADNESS MATH NIGHT WAS A \\nSUCCESSFUL SERVICE PROJECT\\nKINDERGARTEN AND 5TH GRADE READING BUDDIES WENT TO THE PIONEER HOME TO READ TO RESIDENTS!\\xa0\\nMrs. Neufeldt and Dan helped at the Soup-Bowl fundraiser for the \\nFirst City Day Shelter.\\nKCS FEBRUARY SERVICE PROJECT\\nStudents will be making Valentines Day Cards for the \\nLong-Term Patients at the hospital\\nKCS JANUARY SERVICE PROJECT\\nWe are doing an ongoing project that we are calling \\n"STUDENTS IN NEED."\\xa0\\nKCS is colecting items \\n(boots, coats, gloves, etc.) \\nfor students that may be in need.\\nKCS DECEMBER SERVICE PROJECTS\\nBOOKS FOR WISH\\nPLEASE DONATE YOUR GENTLY USED CHILDRENS BOOKS\\nWE WILL BE DELIVERING THE BOOKS TO WISH\\xa0\\nON DECEMBER 21ST\\nDecember 19th:\\xa0 2nd and 3rd Graders are going to the Pioneer Home to Sing and hand out \\nChristmas Cards they made for the residents!\\nKCS NOVEMBER SERVICE PROJECTS\\nKCS students will be working with Operation Gratitude to send Care Packages to Thank the Brave Men and Women who have served or are currently serving in our military around the world. Items that are especially needed are as follows: Instant coffee packets, hot chocolate, tea, card games, small dice games, iTunes cards, walmart gift cards, socks (preferably not white), individual tissue packets, individually packaged wipes, gum or puzzle books. Please make sure food items have at least a six month shelf life.\\nKCS students will be making decorations in art class for the KIC Elder\\\'s Thanksgiving lunceon and dinner.\\nKCS OCTOBER SERVICE PROJECTS\\nMs. Halli participated in the KRBD Public Radio Fund Drive.\\nKCS is helping with the Friends of the Library Book Sale.\\xa0The Book Fair runs from 1-3 on Saturday, October 7, 2017 at the Plaza.\\nKCS is participating in a FLASH LIGHT drive and donating them to Puerto Rico.\\nMrs. Cron\\\'s MS Band and Choir will be preforming for the residents at the Pioneer Home on October 25th.\\xa0\\nSEPTEMBER SERVICE PROJECTS TOTALS\\nWe collected and delivered 235 items of non-perishable food to the Salvation Army.\\nWe collected and donated $183.53 to the Red Cross, Disaster Relief.\\n\\xa0WAY TO GO KCS!\\nPlease note the times below:\\xa0\\n\\xa0Breakfast is served at 7:15!\\nThe gate to the playground doesn\\\'t open until 7:30!\\xa0\\nWe have several students being dropped off early and worry about this being a safety issue.\\xa0\\nFORMS\\nPowerSchool for Parents\\nFAQ\\xa0\\nSchool Start/End Times\\n7:40 AM - 2:30 PM\\nLunch/Recess\\nGrades K-2\\nRecess: 11:10 AM - 11:40 AM\\nLunch: 11:40 AM - 12:00 PM\\nGrades 3-5\\nLunch: 11:30 AM - 12:00 PM\\nRecess: 12:00 PM - 12:30 PM\\nGrades 6-8\\nLunch: 11:30 AM - 12:00 PM\\xa0\\nPlease call the office at 225-8568 by 2:00 so that we have adequate time to deliver notes to your child\\\'s teacher.\\nThank you for your help: We appreciate the advanced notice!\\nComments (-1)\\nSTUDENT DRESS CODE\\nParents are asked to monitor clothing ensuring that the clothing is appropriate for the weather and the activities of the day. Students will be asked to remove, cover-up, or turn inside out any inappropriate clothing worn to school. Any logos on clothing are to be school appropriate. No hoods or hats are to be worn indoors. Students wearing shoes that may be a safety hazard will be asked to change their shoes or limit their activities. Please mark all coats, sweaters, gloves, and hats with the student\\\'s name.\\xa0\\nKCS follows KGBSD\\\'s Dress Code for Elementary and Middle School.\\nComments (-1)\\nHELP RAISE FUNDS FOR KCS\\nCLIP & SAVE BOX TOPS\\nSAVE YOUR A&P RECEIPTS\\nBring your Box Tops and A&P Receipts to the KCS office to help raise funds for our school! \\xa0\\nComments (-1)\\nJOIN OUR APC\\xa0\\nWould you like to become more active at KCS? Come join our APC!\\xa0\\nCLICK HERE FOR AN APPLICATION\\nComments (-1)\\n410 Schoenbar Road\\n\\t\\t\\tKetchikan, AK 99901\\n(907) 225-8568\\n(907) 247-8568\\nQuestions or Feedback?\\n | \\nBlackboard Web Community Manager Privacy Policy (Updated)\\n | \\nTerms of Use\\nCopyright © 2002-2018 Blackboard, Inc. All rights reserved.\\nCLOSE\\nCLOSE\'), (\'https://www.kgbsd.org/ketchikancharter\', \'False\', \'1\', \'Skip to Main Content\\nDistrict Home\\nSelect a School...\\nSelect a School\\nKetchikan High School\\nRevilla High School\\nFast Track\\nSchoenbar Middle School\\nFawn Mountain Elementary School\\nHoughtaling Elementary School\\nPoint Higgins Elementary School\\nKetchikan Charter School (K-8)\\nSign In\\nRegister\\nSearch Our Site\\nHome\\n\\rAbout\\n"\\r\\r\\nSchool Profile\\nKCS School Creed\\nCore Knowledge\\nCore Knowledge Language Arts\\nPearson enVisionmath\\n\\rContact Us\\n"\\r\\r\\nKCS Contact Information\\nStaff Members\\n\\rClasses & Programs\\n"\\r\\nKindergarten - Becky King\\n1st Grade - Maria Neufeldt\\n2nd Grade - Tom Neufeldt\\n3rd Grade - Elizabeth Avila\\n4th Grade - Danielle Hewitt\\n5th Grade - Joelle Gefre\\nLanguage Arts MS - Erin Henderson\\nMath & Science MS - Jacob Alguire\\nSocial Studies & P.E. MS - Greg Gass\\nMusic - Julie Cron\\nTechnology - Julie Cron\\nArt - Halli Kenoyer\\nSpecial Services - Terri Schultz\\nRTI & Testing Coordinator - Kayla Livingston\\nLibrary - Marie Mecham\\nESL - Jane Hanchett\\nJamie Morelli, SLP\\n\\rParents\\n"\\r\\r\\nCharter Chatter\\nReport Card to the Public\\nSchool & Parent Involvement\\nSchool Forms & Documents\\nEnrollment Information\\nBus Schedule\\nenVision Math Parent Guide\\n\\rAPC\\n"\\r\\r\\nAbout the APC\\nPolicy Manual\\nCommittee Members\\nMinutes\\nAgenda\\nPrincipal Evaluation\\n\\rStaff\\n"\\r\\r\\nCalendar\\nUpcoming Events \\nFriday\\nLAST DAY OF SCHOOL\\n8:00 AM - 9:00 AM\\r         \\nEND OF TRIMESTER 3\\nJune 14, 2018\\n6:00 PM - 8:00 PM\\r         \\nAPC MEETING\\nView Calendar\\nMay 29th -\\xa0June 1st\\nMANAGING TIME\\nList all tasks for a particular day or week.\\nEstimate the time needed to complete each task.\\nPlan for delays, setbacks, and problems.\\nImplement a daily schedule that includes planned tasks.\\nEvaluate your time-management plan for effectiveness.\\nComments (-1)\\nComments (-1)\\nComments (-1)\\nCHARTER\\xa0\\nCHATTER\\nSchool News\\nSUMMER ENRICHMENT CAMP AT KCS\\nGrades 1-6, June 11-21st, Monday-Thursday, 8 am - 12 noon\\nThis is a\\xa0\\nfree enrichment program for elementary age \\nstudents to explore their heritage.\\nTo enroll your child, please complete the questions on the form and return \\nto your child\\\'s teacher by June 5th, 2018\\nSummer Enrichment Camp\\nTHE 2017-2018 SCHOOL YEAR IS COMING TO AN END\\nPLEASE MAKE SURE YOUR STUDENT HAS ALL OF THEIR BOOKS TURNED IN AND THEIR LUNCH BALANCES PAID\\nTHE OFFICE WILL BE OPEN UNTIL THE END OF THE DAY ON WEDNESDAY, JUNE 13TH\\nHAVE A GREAT SUMMER!\\xa0\\nLUNCH BALANCE\\nPLEASE CHECK YOUR STUDENTS LUNCH ACCOUNT\\nWE ARE ALMOST AT THE END OF THE SCHOOL YEAR AND WOULD LIKE TO SEE ALL LUNCH ACCOUNTS AT A POSITIVE BALANCE\\nTHANK YOU FOR TAKING CARE OF THIS IN A TIMELY MANNER!\\nKCS 8th GRADE GRADUATION\\nJUNE 5TH\\n6:00 PM IN THE KCS GYM\\nKETCHIKAN CHARTER/MIDDLE SCHOOL\\n2018-2019\\nENROLLMENT IS NOW OPEN\\nKCS is now accepting registration for the 2018-2019 school year.\\nRegistration packets are online or you\\nmay stop by the office anytime, \\nM-F from 7:45 am - 3:15 pm, to pick up a registration packet.\\xa0\\nSpace is limited, so it is very important to return the registration packet \\nalong with your child\\\'s \\nbirth certificate and immunization records.\\xa0\\nIf your student is already enrolled in another school in the district and wanting to transfer to KCS stop by the office to fill out a transfer form.\\nKetchikan Charter School is Celebrating their 20th Anniversary this year\\nOur school will be hosting and participating in several events throughout the year-the largest of which being 20 community service projects.\\nWe plan to have two events per month and hope to raise the public\\\'s awareness of our school and how much we appreciate them, and that we are a longstanding part of this community.\\nWe hope to serve the community through education.\\nKCS MAY SERVICE PROJECTS\\nMIDDLE SCHOOL WILL HAVE A CLEANUP AS PART \\nOF THEIR CAMPING EXPERIENCE.\\nROBOTICS WILL BE ORGANIZING A FOOD DRIVE.\\n3rd and 4th Grade Beach Cleanup May 22nd\\xa0\\nKCS APRIL SERVICE PROJECTS\\nKINDERGARTEN AND 5TH GRADE WILL HAVE AN \\nEARTH DAY CLEANUP ON APRIL 20TH\\nKCS MARCH SERVICE PROJECTS\\nWe will be working with the \\nFirst City Council on Cancer.\\nMARCH MADNESS MATH NIGHT WAS A \\nSUCCESSFUL SERVICE PROJECT\\nKINDERGARTEN AND 5TH GRADE READING BUDDIES WENT TO THE PIONEER HOME TO READ TO RESIDENTS!\\xa0\\nMrs. Neufeldt and Dan helped at the Soup-Bowl fundraiser for the \\nFirst City Day Shelter.\\nKCS FEBRUARY SERVICE PROJECT\\nStudents will be making Valentines Day Cards for the \\nLong-Term Patients at the hospital\\nKCS JANUARY SERVICE PROJECT\\nWe are doing an ongoing project that we are calling \\n"STUDENTS IN NEED."\\xa0\\nKCS is colecting items \\n(boots, coats, gloves, etc.) \\nfor students that may be in need.\\nKCS DECEMBER SERVICE PROJECTS\\nBOOKS FOR WISH\\nPLEASE DONATE YOUR GENTLY USED CHILDRENS BOOKS\\nWE WILL BE DELIVERING THE BOOKS TO WISH\\xa0\\nON DECEMBER 21ST\\nDecember 19th:\\xa0 2nd and 3rd Graders are going to the Pioneer Home to Sing and hand out \\nChristmas Cards they made for the residents!\\nKCS NOVEMBER SERVICE PROJECTS\\nKCS students will be working with Operation Gratitude to send Care Packages to Thank the Brave Men and Women who have served or are currently serving in our military around the world. Items that are especially needed are as follows: Instant coffee packets, hot chocolate, tea, card games, small dice games, iTunes cards, walmart gift cards, socks (preferably not white), individual tissue packets, individually packaged wipes, gum or puzzle books. Please make sure food items have at least a six month shelf life.\\nKCS students will be making decorations in art class for the KIC Elder\\\'s Thanksgiving lunceon and dinner.\\nKCS OCTOBER SERVICE PROJECTS\\nMs. Halli participated in the KRBD Public Radio Fund Drive.\\nKCS is helping with the Friends of the Library Book Sale.\\xa0The Book Fair runs from 1-3 on Saturday, October 7, 2017 at the Plaza.\\nKCS is participating in a FLASH LIGHT drive and donating them to Puerto Rico.\\nMrs. Cron\\\'s MS Band and Choir will be preforming for the residents at the Pioneer Home on October 25th.\\xa0\\nSEPTEMBER SERVICE PROJECTS TOTALS\\nWe collected and delivered 235 items of non-perishable food to the Salvation Army.\\nWe collected and donated $183.53 to the Red Cross, Disaster Relief.\\n\\xa0WAY TO GO KCS!\\nPlease note the times below:\\xa0\\n\\xa0Breakfast is served at 7:15!\\nThe gate to the playground doesn\\\'t open until 7:30!\\xa0\\nWe have several students being dropped off early and worry about this being a safety issue.\\xa0\\nFORMS\\nPowerSchool for Parents\\nFAQ\\xa0\\nSchool Start/End Times\\n7:40 AM - 2:30 PM\\nLunch/Recess\\nGrades K-2\\nRecess: 11:10 AM - 11:40 AM\\nLunch: 11:40 AM - 12:00 PM\\nGrades 3-5\\nLunch: 11:30 AM - 12:00 PM\\nRecess: 12:00 PM - 12:30 PM\\nGrades 6-8\\nLunch: 11:30 AM - 12:00 PM\\xa0\\nPlease call the office at 225-8568 by 2:00 so that we have adequate time to deliver notes to your child\\\'s teacher.\\nThank you for your help: We appreciate the advanced notice!\\nComments (-1)\\nSTUDENT DRESS CODE\\nParents are asked to monitor clothing ensuring that the clothing is appropriate for the weather and the activities of the day. Students will be asked to remove, cover-up, or turn inside out any inappropriate clothing worn to school. Any logos on clothing are to be school appropriate. No hoods or hats are to be worn indoors. Students wearing shoes that may be a safety hazard will be asked to change their shoes or limit their activities. Please mark all coats, sweaters, gloves, and hats with the student\\\'s name.\\xa0\\nKCS follows KGBSD\\\'s Dress Code for Elementary and Middle School.\\nComments (-1)\\nHELP RAISE FUNDS FOR KCS\\nCLIP & SAVE BOX TOPS\\nSAVE YOUR A&P RECEIPTS\\nBring your Box Tops and A&P Receipts to the KCS office to help raise funds for our school! \\xa0\\nComments (-1)\\nJOIN OUR APC\\xa0\\nWould you like to become more active at KCS? Come join our APC!\\xa0\\nCLICK HERE FOR AN APPLICATION\\nComments (-1)\\n410 Schoenbar Road\\n\\t\\t\\tKetchikan, AK 99901\\n(907) 225-8568\\n(907) 247-8568\\nQuestions or Feedback?\\n | \\nBlackboard Web Community Manager Privacy Policy (Updated)\\n | \\nTerms of Use\\nCopyright © 2002-2018 Blackboard, Inc. All rights reserved.\\nCLOSE\\nCLOSE\')]'

In [8]:
df["text_full"]

0       [('http://www.maef.net/', 'False', '0', "Menu\...
1       [('https://www.kgbsd.org/ketchikancharter', 'F...
2       [('http://tongassschool.org/', 'False', '0', '...
3       [('https://www.asdk12.org/aquarian', 'False', ...
4       [('http://winterberrycharterschool.com/', 'Fal...
                              ...
6458    [('http://www.snowyrangeacademy.org/', 'False'...
6459    [('http://www.laramiemontessori.org/index.html...
6460    [('https://www.fcsd38.org/', 'False', '0', "Fr...
6461    [('https://poderacademy.com/', 'False', '0', '...
6462    [('https://poderacademy.com/', 'False', '0', '...
Name: text_full, Length: 6463, dtype: object

In [9]:
def count_pages(text):
    counter = 0 #count the number of urls 
    http_array = []
    for i in text:
        if i=='h':
            http_array.append("h")
        if i == 't' and len(http_array)== 1 and http_array[0] == 'h':
            http_array.append("t")
        if i == 't' and len(http_array)== 2 and http_array[1] == 't':
            http_array.append("t") 
        if i == 'p' and len(http_array)== 3 and http_array[2] == 't':
            print(http_array)
            counter += 1
            http_array = []
    return counter

In [10]:
count_pages(df["text_full"][0])

['h', 't', 't']
['h', 't', 't']
['h', 't', 't']

3

In [11]:
count_pages(df["text_full"][7])

['h', 't', 't']

1

In [12]:
text = df["text_full"][0]
urls = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', text) #used regex to find the list of urls within full text. 
#print("Original string: ",text)
print("Urls: ",urls)
len(urls) #Total number of urls within the text

Urls:  ["http://www.maef.net/',", "http://www.maef.net/',", "http://www.maef.net/about/',", "http://www.maef.net/college-career-indicator-dashboard/',", "http://www.maef.net/contact/',", "http://www.maef.net/event/accel-informational-meetings/',", "http://www.maef.net/event/accel-is-now-accepting-applications/',", "http://www.maef.net/event/new-student-orientation/',", "http://www.maef.net/featured/u-s-education-secretary-visits-mobile/',", "http://www.maef.net/featured/whats-working/',", "http://www.maef.net/news-media/',", "http://www.maef.net/our-impact/',", "http://www.maef.net/our-work/',", "http://www.maef.net/our-work/initiatives/75k-degrees/',", "http://www.maef.net/our-work/initiatives/evidence2success/',", "http://www.maef.net/our-work/initiatives/graduate-ready',", "http://www.maef.net/our-work/initiatives/graduate-ready/',", "http://www.maef.net/our-work/initiatives/yes-we-can/',", "http://www.maef.net/our-work/programs/accel/',", "http://www.maef.net/our-work/programs/education-commission/',", "http://www.maef.net/our-work/programs/eye/',", "http://www.maef.net/our-work/programs/fund-a-star/',", "http://www.maef.net/our-work/programs/partners/',", "http://www.maef.net/our-work/programs/ramp/',", "http://www.maef.net/our-work/programs/reading-buddy/',", "http://www.maef.net/our-work/programs/student-advisory-council/',", "http://www.maef.net/our-work/programs/vital-link/',", "http://www.maef.net/support/',", "http://www.maef.net/?p=1040',", "http://www.maef.net/?p=1043',", "http://www.maef.net/?p=1149',", "http://www.maef.net/Loss%20of%20assistant%20principals%20spreads%20Mobile%20County%20school%20staffs%20thin',", "http://www.maef.net/graduate-ready-articles/save-the-date-for-the-14th-annual-education-summit/',", "http://www.maef.net/photos.al.com/mobile-press-register/2010/01/george_hall_being_filmed_5.html',", "http://www.maef.net/uncategorized/graduate-ready-summit/',", "http://www.maef.net/uncategorized/maef-ceo-takes-ice-bucket-challenge-for-als/',", "http://www.maef.net/our-work/programs/student-advisory-council/attachment/equity-report-2016/',", "http://www.maef.net/support',", "http://www.maef.net/volunteer/',", "http://www.maef.net/accel-merit-scholar-awards/',", "http://www.maef.net/accel-photo-gallery/',", "http://www.maef.net/graduate-ready-articles/maef-gets-approval-for-alabamas-first-charter-school/',", "http://www.maef.net/four-strategic-priorities/college-and-career-resources/',", "http://www.maef.net/thank-you/',", "http://www.maef.net/support/volunteer/',"]

45

In [13]:
def count_urls(text):
    urls = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', text)
    return len(urls)

In [14]:
count_urls(df["text_full"][0])

45

In [15]:
df_out = df[['text_full']]

In [16]:
df_out

                                              text_full
0     [('http://www.maef.net/', 'False', '0', "Menu\...
1     [('https://www.kgbsd.org/ketchikancharter', 'F...
2     [('http://tongassschool.org/', 'False', '0', '...
3     [('https://www.asdk12.org/aquarian', 'False', ...
4     [('http://winterberrycharterschool.com/', 'Fal...
...                                                 ...
6458  [('http://www.snowyrangeacademy.org/', 'False'...
6459  [('http://www.laramiemontessori.org/index.html...
6460  [('https://www.fcsd38.org/', 'False', '0', "Fr...
6461  [('https://poderacademy.com/', 'False', '0', '...
6462  [('https://poderacademy.com/', 'False', '0', '...

[6463 rows x 1 columns]

In [17]:
count_urls_array = []
for i in range(6463):
    count=count_urls(df["text_full"][i])
    count_urls_array.append(count)
count_urls_array

[45,
 2,
 132,
 1,
 37,
 36,
 1,
 1,
 1,
 12,
 272,
 13,
 201,
 2,
 4,
 1,
 30,
 2,
 84,
 2,
 2,
 2,
 5,
 4,
 2,
 5,
 4,
 61,
 153,
 4,
 23,
 59,
 2,
 126,
 113,
 8,
 25,
 25,
 28,
 9,
 54,
 609,
 279,
 2,
 194,
 155,
 167,
 9,
 487,
 35,
 2,
 195,
 238,
 217,
 217,
 13,
 137,
 95,
 263,
 230,
 87,
 33,
 50,
 138,
 6,
 4,
 171,
 24,
 20,
 18,
 41,
 41,
 68,
 1,
 1,
 1,
 1026,
 1,
 1,
 63,
 60,
 17,
 86,
 39,
 17,
 1,
 370,
 176,
 112,
 1,
 167,
 85,
 19,
 21,
 21,
 20,
 118,
 205,
 1,
 23,
 23,
 23,
 13,
 23,
 37,
 94,
 104,
 87,
 672,
 703,
 112,
 77,
 1026,
 61,
 79,
 7,
 10,
 93,
 43,
 7,
 262,
 365,
 292,
 272,
 3,
 3,
 99,
 3,
 2,
 2,
 35,
 306,
 24,
 16,
 182,
 128,
 72,
 2,
 21,
 233,
 12,
 214,
 189,
 201,
 153,
 1,
 10,
 22,
 228,
 163,
 213,
 213,
 136,
 78,
 25,
 12,
 94,
 95,
 53,
 50,
 18,
 28,
 8,
 2,
 2,
 1,
 25,
 11,
 6,
 141,
 22,
 15,
 41,
 397,
 82,
 124,
 378,
 95,
 3,
 3,
 3,
 331,
 3,
 99,
 1,
 300,
 1,
 7,
 45,
 91,
 11,
 9,
 612,
 55,
 52,
 3,
 155,
 247,
 272,
 204,
 63,
 35,
 190,
 1,
 339,
 21,
 13,
 1,
 24,
 109,
 6,
 23,
 44,
 44,
 8,
 47,
 143,
 18,
 1,
 30,
 99,
 14,
 16,
 12,
 3,
 50,
 51,
 1,
 46,
 84,
 188,
 286,
 77,
 77,
 77,
 76,
 77,
 20,
 48,
 12,
 2,
 50,
 123,
 77,
 152,
 1,
 28,
 13,
 142,
 117,
 113,
 17,
 2,
 108,
 15,
 29,
 669,
 67,
 1,
 2,
 1,
 131,
 179,
 178,
 142,
 119,
 71,
 76,
 9,
 161,
 217,
 179,
 2,
 2,
 2,
 169,
 3,
 40,
 3,
 85,
 6,
 7,
 11,
 4,
 12,
 122,
 74,
 100,
 107,
 78,
 33,
 122,
 117,
 3,
 122,
 2,
 1,
 1,
 42,
 15,
 2,
 4,
 172,
 121,
 70,
 46,
 25,
 24,
 77,
 145,
 71,
 48,
 59,
 1,
 446,
 68,
 72,
 139,
 2,
 5,
 1,
 5,
 2,
 8,
 1,
 165,
 213,
 60,
 120,
 148,
 25,
 26,
 86,
 66,
 52,
 31,
 1,
 40,
 274,
 306,
 34,
 24,
 2,
 9,
 67,
 138,
 159,
 59,
 2,
 226,
 1,
 120,
 2,
 2,
 5,
 145,
 48,
 103,
 65,
 391,
 125,
 222,
 208,
 93,
 103,
 3,
 27,
 133,
 184,
 13,
 64,
 180,
 251,
 174,
 192,
 31,
 54,
 63,
 1,
 39,
 53,
 88,
 32,
 86,
 295,
 75,
 6,
 1,
 56,
 1,
 326,
 1,
 1,
 1,
 1,
 46,
 64,
 37,
 106,
 26,
 45,
 47,
 79,
 50,
 43,
 4,
 197,
 126,
 2,
 25,
 49,
 2,
 2,
 88,
 70,
 8,
 1,
 20,
 20,
 145,
 19,
 193,
 2,
 10,
 28,
 27,
 48,
 64,
 100,
 38,
 1,
 1,
 49,
 1,
 3,
 5,
 50,
 35,
 60,
 99,
 122,
 127,
 155,
 1,
 95,
 65,
 103,
 33,
 1,
 48,
 61,
 18,
 39,
 125,
 98,
 69,
 48,
 27,
 66,
 3,
 3,
 3,
 104,
 70,
 145,
 109,
 93,
 58,
 136,
 23,
 44,
 17,
 104,
 8,
 96,
 27,
 64,
 49,
 92,
 47,
 18,
 31,
 2,
 90,
 38,
 99,
 24,
 90,
 15,
 3,
 3,
 102,
 176,
 101,
 2,
 71,
 46,
 64,
 102,
 20,
 45,
 199,
 31,
 3,
 114,
 119,
 289,
 72,
 145,
 1,
 24,
 23,
 69,
 150,
 36,
 86,
 186,
 7,
 16,
 228,
 158,
 151,
 66,
 47,
 1062,
 85,
 72,
 60,
 35,
 40,
 31,
 288,
 3,
 83,
 183,
 83,
 387,
 50,
 57,
 135,
 56,
 139,
 11,
 69,
 22,
 40,
 62,
 2,
 45,
 1,
 35,
 2,
 93,
 329,
 174,
 1679,
 292,
 161,
 40,
 156,
 143,
 3,
 225,
 123,
 211,
 135,
 78,
 2,
 3,
 2,
 2,
 2,
 50,
 2,
 2,
 2,
 2,
 2,
 3,
 118,
 97,
 3,
 3,
 32,
 1,
 1,
 2,
 3,
 3,
 3,
 3,
 727,
 648,
 6,
 6,
 8,
 3,
 3,
 3,
 25,
 549,
 3,
 3,
 3,
 95,
 169,
 23,
 13,
 151,
 214,
 700,
 1,
 17,
 61,
 24,
 1,
 805,
 64,
 48,
 21,
 27,
 164,
 249,
 185,
 19,
 3,
 212,
 2,
 56,
 55,
 1,
 105,
 475,
 198,
 2,
 212,
 282,
 45,
 116,
 81,
 109,
 159,
 189,
 81,
 384,
 438,
 273,
 41,
 282,
 168,
 1,
 25,
 4,
 298,
 220,
 151,
 29,
 1,
 1654,
 26,
 2,
 3,
 606,
 2,
 316,
 508,
 194,
 291,
 45,
 114,
 145,
 26,
 1138,
 3,
 3,
 3,
 1074,
 973,
 440,
 128,
 166,
 52,
 146,
 397,
 171,
 322,
 120,
 304,
 235,
 378,
 42,
 37,
 38,
 29,
 24,
 37,
 36,
 1073,
 68,
 99,
 484,
 1189,
 31,
 75,
 2,
 219,
 2,
 44,
 164,
 162,
 68,
 44,
 21,
 103,
 56,
 38,
 15,
 1468,
 348,
 865,
 87,
 208,
 83,
 50,
 68,
 619,
 122,
 7,
 25,
 3,
 79,
 138,
 91,
 27,
 1,
 1,
 51,
 1,
 1,
 49,
 22,
 2,
 3,
 2,
 3,
 7,
 1,
 904,
 41,
 130,
 20,
 105,
 13,
 49,
 46,
 49,
 45,
 53,
 464,
 104,
 64,
 49,
 1,
 11,
 20,
 2,
 1,
 48,
 75,
 2,
 1,
 1,
 510,
 72,
 50,
 41,
 50,
 50,
 1530,
 357,
 30,
 238,
 11,
 1,
 31,
 1,
 1,
 4,
 4,
 4,
 4,
 62,
 424,
 638,
 475,
 447,
 615,
 589,
 813,
 1065,
 614,
 596,
 450,
 91,
 347,
 16,
 117,
 101,
 215,
 30,
 2,
 41,
 1,
 2,
 4,
 6,
 64,
 66,
 93,
 56,
 263,
 38,
 96,
 1,
 1,
 1,
 2,
 20,
 2,
 65,
 126,
 59,
 128,
 86,
 30,
 345,
 82,
 114,
 432,
 233,
 221,
 558,
 515,
 2,
 43,
 3,
 11,
 225,
 51,
 2,
 621,
 108,
 81,
 1,
 10,
 1,
 129,
 44,
 54,
 83,
 67,
 85,
 62,
 3,
 86,
 3,
 6,
 25,
 118,
 47,
 83,
 34,
 33,
 72,
 132,
 1,
 373,
 10,
 99,
 52,
 39,
 29,
 30,
 33,
 56,
 2,
 1,
 155,
 100,
 245,
 52,
 26,
 2,
 2,
 41,
 3,
 384,
 19,
 2,
 3,
 1,
 50,
 178,
 171,
 194,
 53,
 167,
 125,
 877,
 33,
 14,
 20,
 2,
 146,
 174,
 542,
 26,
 170,
 30,
 869,
 245,
 49,
 56,
 178,
 60,
 336,
 840,
 79,
 337,
 193,
 167,
 130,
 52,
 119,
 134,
 120,
 29,
 99,
 1,
 124,
 37,
 152,
 227,
 104,
 106,
 104,
 6,
 42,
 11,
 59,
 52,
 168,
 38,
 1,
 81,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 276,
 37,
 32,
 39,
 51,
 1295,
 105,
 2,
 1,
 32,
 49,
 187,
 43,
 357,
 104,
 142,
 31,
 48,
 3,
 96,
 6,
 1,
 1,
 1287,
 6,
 103,
 1,
 3,
 3,
 59,
 411,
 53,
 183,
 78,
 1277,
 537,
 2,
 1353,
 ...]

In [18]:
len(count_urls_array)

6463

In [19]:
df['Page Count'] = count_urls_array

In [20]:
df

,Unnamed: 0,text_full,NCESSCH,Page Count
0,0,"[('http://www.maef.net/', 'False', '0', ""Menu\...",1.001970e+10,45
1,1,"[('https://www.kgbsd.org/ketchikancharter', 'F...",2.001500e+10,2
2,2,"[('http://tongassschool.org/', 'False', '0', '...",2.001500e+10,132
3,3,"[('https://www.asdk12.org/aquarian', 'False', ...",2.001800e+10,1
4,4,"[('http://winterberrycharterschool.com/', 'Fal...",2.001800e+10,37
...,...,...,...,...
6458,6458,"[('http://www.snowyrangeacademy.org/', 'False'...",5.600730e+11,30
6459,6459,[('http://www.laramiemontessori.org/index.html...,5.600730e+11,1
6460,6460,"[('https://www.fcsd38.org/', 'False', '0', ""Fr...",5.600960e+11,53
6461,6461,"[('https://poderacademy.com/', 'False', '0', '...",5.601980e+11,25
6462,6462,"[('https://poderacademy.com/', 'False', '0', '...",5.601980e+11,46

In [29]:
count_urls_full_array = []
for i in range(len(df_full)):
    count=count_urls(df_full["text_full"][i])
    count_urls_full_array.append(count)
count_urls_full_array

[698,
 654,
 247,
 58,
 1,
 113,
 348,
 396,
 59,
 22,
 41,
 24,
 359,
 363,
 221,
 138,
 92,
 16,
 251,
 2,
 24,
 48,
 45,
 238,
 38,
 17,
 53,
 2,
 204,
 26,
 7,
 45,
 27,
 72,
 150,
 203,
 169,
 208,
 77,
 123,
 35,
 33,
 197,
 1,
 135,
 41,
 1,
 1183,
 2,
 22,
 40,
 1,
 157,
 41,
 36,
 279,
 11,
 11,
 672,
 33,
 89,
 15,
 56,
 266,
 90,
 31,
 47,
 48,
 494,
 1,
 99,
 3,
 3,
 3,
 23,
 23,
 1,
 56,
 87,
 2,
 85,
 886,
 105,
 1,
 1,
 62,
 3,
 3,
 50,
 90,
 99,
 93,
 99,
 122,
 510,
 88,
 120,
 70,
 26,
 1,
 76,
 594,
 225,
 3,
 3,
 3,
 31,
 3,
 2,
 249,
 1,
 250,
 1,
 10,
 21,
 54,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 135,
 81,
 61,
 19,
 32,
 216,
 302,
 182,
 52,
 79,
 511,
 5,
 71,
 85,
 69,
 11,
 35,
 61,
 56,
 1,
 80,
 80,
 3,
 148,
 11,
 20,
 17,
 120,
 45,
 35,
 93,
 25,
 60,
 46,
 50,
 31,
 35,
 40,
 92,
 73,
 32,
 117,
 1634,
 105,
 97,
 66,
 469,
 31,
 26,
 42,
 1,
 8,
 39,
 25,
 1277,
 80,
 700,
 83,
 2,
 41,
 35,
 397,
 36,
 48,
 120,
 56,
 39,
 82,
 218,
 10,
 119,
 1,
 19,
 25,
 20,
 20,
 424,
 271,
 316,
 3,
 3,
 174,
 66,
 142,
 1530,
 263,
 216,
 59,
 1,
 70,
 239,
 1,
 27,
 34,
 40,
 177,
 321,
 245,
 32,
 85,
 70,
 37,
 69,
 128,
 51,
 38,
 140,
 35,
 80,
 36,
 2,
 87,
 157,
 345,
 22,
 34,
 81,
 117,
 4,
 1,
 33,
 128,
 25,
 46,
 3,
 3,
 36,
 29,
 30,
 28,
 23,
 32,
 26,
 36,
 23,
 42,
 28,
 36,
 75,
 13,
 25,
 94,
 95,
 95,
 146,
 220,
 109,
 2,
 112,
 213,
 91,
 193,
 32,
 260,
 40,
 28,
 21,
 339,
 63,
 25,
 23,
 26,
 38,
 47,
 4,
 219,
 102,
 97,
 352,
 22,
 475,
 103,
 104,
 104,
 104,
 104,
 104,
 104,
 104,
 104,
 104,
 1155,
 1,
 31,
 115,
 81,
 99,
 11,
 345,
 370,
 364,
 8,
 8,
 149,
 66,
 72,
 143,
 2,
 115,
 94,
 49,
 222,
 123,
 60,
 50,
 53,
 66,
 33,
 17,
 118,
 199,
 293,
 37,
 1,
 49,
 42,
 265,
 901,
 580,
 38,
 48,
 91,
 37,
 19,
 21,
 9,
 25,
 39,
 102,
 1,
 279,
 16,
 71,
 27,
 8,
 140,
 145,
 13,
 233,
 1679,
 94,
 368,
 9,
 426,
 29,
 36,
 74,
 20,
 2,
 210,
 567,
 2,
 287,
 239,
 19,
 39,
 384,
 4,
 192,
 232,
 222,
 182,
 29,
 17,
 875,
 412,
 40,
 1,
 63,
 27,
 165,
 40,
 189,
 1,
 496,
 26,
 35,
 432,
 150,
 35,
 168,
 230,
 53,
 12,
 50,
 137,
 12,
 233,
 6,
 76,
 29,
 91,
 63,
 64,
 48,
 38,
 191,
 1435,
 57,
 48,
 41,
 94,
 43,
 50,
 83,
 2,
 1339,
 196,
 40,
 1,
 65,
 515,
 348,
 67,
 39,
 14,
 144,
 1,
 61,
 437,
 18,
 33,
 26,
 32,
 64,
 76,
 8,
 274,
 306,
 169,
 41,
 36,
 9,
 45,
 40,
 41,
 43,
 1,
 42,
 37,
 366,
 37,
 15,
 34,
 21,
 40,
 282,
 12,
 12,
 41,
 187,
 12,
 121,
 41,
 119,
 72,
 221,
 64,
 273,
 45,
 36,
 41,
 41,
 126,
 50,
 153,
 46,
 91,
 67,
 10,
 1,
 1,
 865,
 2019,
 1468,
 221,
 71,
 48,
 75,
 39,
 69,
 72,
 11,
 12,
 197,
 836,
 874,
 90,
 40,
 877,
 2,
 2,
 38,
 206,
 1,
 91,
 11,
 18,
 1287,
 144,
 29,
 125,
 2,
 1,
 207,
 130,
 1,
 1,
 1,
 1,
 1,
 2,
 373,
 91,
 124,
 143,
 296,
 303,
 170,
 77,
 51,
 39,
 1463,
 64,
 4,
 4,
 44,
 78,
 79,
 28,
 28,
 36,
 28,
 44,
 17,
 16,
 17,
 17,
 150,
 111,
 63,
 45,
 1,
 272,
 91,
 124,
 162,
 166,
 82,
 29,
 39,
 37,
 4,
 4,
 183,
 49,
 138,
 2,
 2,
 24,
 32,
 51,
 58,
 322,
 92,
 28,
 15,
 39,
 1056,
 61,
 135,
 52,
 2,
 255,
 15,
 1,
 1,
 61,
 178,
 52,
 85,
 272,
 173,
 314,
 376,
 312,
 153,
 4,
 43,
 101,
 1,
 30,
 81,
 182,
 208,
 8,
 447,
 102,
 71,
 200,
 67,
 81,
 577,
 41,
 24,
 62,
 21,
 1,
 105,
 13,
 92,
 36,
 76,
 2,
 191,
 86,
 8,
 8,
 33,
 108,
 49,
 151,
 292,
 530,
 3,
 24,
 38,
 104,
 24,
 17,
 47,
 71,
 439,
 407,
 94,
 708,
 65,
 152,
 64,
 24,
 56,
 83,
 182,
 87,
 71,
 151,
 487,
 20,
 214,
 56,
 101,
 118,
 40,
 72,
 33,
 14,
 10,
 109,
 745,
 143,
 263,
 65,
 1,
 1,
 3,
 3,
 68,
 54,
 66,
 299,
 102,
 405,
 3,
 234,
 30,
 96,
 97,
 118,
 169,
 38,
 151,
 20,
 205,
 52,
 31,
 58,
 77,
 38,
 142,
 263,
 166,
 870,
 25,
 44,
 46,
 1,
 64,
 80,
 1138,
 97,
 705,
 79,
 103,
 59,
 336,
 337,
 146,
 26,
 130,
 103,
 93,
 126,
 167,
 162,
 72,
 75,
 1,
 47,
 397,
 170,
 19,
 55,
 77,
 205,
 1,
 176,
 70,
 75,
 119,
 68,
 134,
 681,
 3,
 93,
 2,
 131,
 2,
 61,
 186,
 62,
 132,
 34,
 249,
 205,
 225,
 305,
 386,
 25,
 77,
 83,
 144,
 130,
 57,
 39,
 34,
 55,
 91,
 50,
 41,
 53,
 59,
 60,
 96,
 43,
 54,
 48,
 49,
 51,
 40,
 59,
 145,
 47,
 114,
 9,
 3,
 109,
 128,
 59,
 97,
 165,
 129,
 71,
 44,
 130,
 109,
 136,
 15,
 37,
 43,
 72,
 982,
 1295,
 122,
 47,
 107,
 72,
 107,
 50,
 148,
 76,
 1,
 51,
 50,
 69,
 69,
 53,
 52,
 92,
 38,
 17,
 254,
 56,
 44,
 27,
 49,
 50,
 50,
 185,
 1,
 67,
 71,
 172,
 97,
 145,
 67,
 221,
 108,
 4,
 4,
 157,
 168,
 484,
 28,
 66,
 989,
 47,
 73,
 110,
 115,
 103,
 3,
 2,
 133,
 368,
 39,
 168,
 17,
 91,
 158,
 193,
 290,
 12,
 1,
 201,
 159,
 11,
 6,
 4,
 102,
 34,
 29,
 96,
 62,
 228,
 263,
 259,
 52,
 64,
 82,
 13,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 3,
 3,
 55,
 77,
 47,
 4,
 2,
 49,
 3,
 3,
 279,
 5,
 1,
 9,
 10,
 16,
 16,
 16,
 23,
 14,
 66,
 168,
 1,
 129,
 357,
 128,
 11,
 2,
 3,
 39,
 11,
 82,
 130,
 17,
 1,
 63,
 70,
 74,
 92,
 44,
 62,
 73,
 184,
 11,
 414,
 24,
 120,
 62,
 13,
 33,
 63,
 1214,
 44,
 35,
 10,
 515,
 1,
 246,
 508,
 50,
 79,
 504,
 76,
 77,
 77,
 75,
 42,
 18,
 90,
 1,
 134,
 69,
 62,
 69,
 104,
 4,
 139,
 194,
 28,
 598,
 43,
 1,
 46,
 357,
 51,
 75,
 212,
 70,
 114,
 11,
 48,
 50,
 164,
 512,
 23,
 86,
 70,
 ...]

In [30]:
len(count_urls_full_array)

6504

In [32]:
df_full['Page Count'] = count_urls_full_array

In [38]:
df_full_filtered = df_full[df_full['Page Count'] <= 250]

In [39]:
df_full_filtered

,Unnamed: 0,text_full,NCESSCH,Page Count
2,2,"[('http://21stcenturypa.com/wp/', 'False', '0'...",350006000811,247
3,3,"[('http://a3school.org/', 'False', '0', 'Downl...",411167001641,58
4,4,"[('https://www.aaechighschools.com/index.php',...",40010601892,1
5,5,"[('https://aaiutah.org/', 'False', '0', ""SCHOO...",490018601483,113
8,8,"[('http://aca.vail.k12.az.us/', 'False', '0', ...",40885001510,59
...,...,...,...,...
6499,6499,"[('https://youth-ranch.org/', 'False', '0', ' ...",480022711321,108
6500,6500,[('https://zenithacademy.squarespace.com/zenit...,390157605848,2
6501,6501,[('https://zenithacademy.squarespace.com/zenit...,390139605579,1
6502,6502,[('https://www.kippdc.org/our-schools/kipp-dc-...,110003100427,3
6503,6503,[('https://www.kippdc.org/our-schools/kipp-dc-...,110003100452,3

In [41]:
df_filtered_greater_250 = df[df['Page Count'] >= 250]

In [42]:
df_filtered_greater_250

,Unnamed: 0,text_full,NCESSCH,Page Count
10,10,[('http://fireweedacademy.blogs.kpbsd.k12.ak.u...,2.003900e+10,272
41,41,"[('http://www.srpmic-ed.org/', 'False', '0', '...",4.000470e+10,609
42,42,"[('http://ala.srpmic-ed.org/', 'False', '0', '...",4.000470e+10,279
48,48,"[('https://www.goasa.org/', 'False', '0', ""Ari...",4.000560e+10,487
58,58,"[('https://khalsamontessori.org/', 'False', '0...",4.000690e+10,263
...,...,...,...,...
6431,6431,"[('http://www.flambeau.k12.wi.us/', 'False', '...",5.514970e+11,481
6434,6434,"[('http://ckcs.verona.k12.wi.us/', 'False', '0...",5.515330e+11,368
6447,6447,"[('http://montessori.wausauschools.org/', 'Fal...",5.515900e+11,250
6452,6452,"[('http://sharedjourneys.wawm.k12.wi.us/', 'Fa...",5.516260e+11,452
6455,6455,"[('http://www.wegafremont.k12.wi.us/', 'False'...",5.516500e+11,453